# Change these first
owner: HoscoHarding # Your GitHub username
repo: P-ginasPrueba # Your Github repository name

# Add your sites here
sites:
  - name: GuessEU
    url: https://www.guess.eu
  - name: Guess.CA
    url: https://www.guess.com/ca/en/home/?changeCountry=1
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: Broken Site
    url: https://thissitedoesnotexist.com
  - name: Secret Site
    url: $SECRET_SITE

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: HolaBuenas
  introTitle: Chequeame esta
  introMessage: Vamos a ver que tal
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
